/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminStats = IDL.Record({
  'activeUsers' : IDL.Nat,
  'totalQuotes' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'paidQuotes' : IDL.Nat,
  'pendingQuotes' : IDL.Nat,
});
export const Quote = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null }),
  'clientName' : IDL.Text,
  'planId' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'clientEmail' : IDL.Text,
  'agentName' : IDL.Text,
  'coverageAmount' : IDL.Nat,
  'clientAge' : IDL.Nat,
  'planName' : IDL.Text,
  'paidAt' : IDL.Opt(IDL.Int),
  'monthlyPremium' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'lastActivity' : IDL.Int,
  'role' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'registeredAt' : IDL.Int,
});
export const InsurancePlan = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'coverageAmount' : IDL.Nat,
  'benefits' : IDL.Vec(IDL.Text),
  'monthlyPremium' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInsurancePlan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createQuote' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlans' : IDL.Func([], [IDL.Vec(InsurancePlan)], ['query']),
  'getQuotesByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Quote)], []),
  'getUserById' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'logout' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'markQuotePaid' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Principal],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserActive' : IDL.Func([IDL.Principal, IDL.Bool], [IDL.Bool], []),
  'updateUserRole' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
  'validateSession' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Tuple(IDL.Principal, IDL.Text))],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminStats = IDL.Record({
    'activeUsers' : IDL.Nat,
    'totalQuotes' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'paidQuotes' : IDL.Nat,
    'pendingQuotes' : IDL.Nat,
  });
  const Quote = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null }),
    'clientName' : IDL.Text,
    'planId' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'clientEmail' : IDL.Text,
    'agentName' : IDL.Text,
    'coverageAmount' : IDL.Nat,
    'clientAge' : IDL.Nat,
    'planName' : IDL.Text,
    'paidAt' : IDL.Opt(IDL.Int),
    'monthlyPremium' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'lastActivity' : IDL.Int,
    'role' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'registeredAt' : IDL.Int,
  });
  const InsurancePlan = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'coverageAmount' : IDL.Nat,
    'benefits' : IDL.Vec(IDL.Text),
    'monthlyPremium' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInsurancePlan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createQuote' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlans' : IDL.Func([], [IDL.Vec(InsurancePlan)], ['query']),
    'getQuotesByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Quote)], []),
    'getUserById' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'logout' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'markQuotePaid' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Principal],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserActive' : IDL.Func([IDL.Principal, IDL.Bool], [IDL.Bool], []),
    'updateUserRole' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
    'validateSession' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Tuple(IDL.Principal, IDL.Text))],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };