/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'activeUsers' : bigint,
  'totalQuotes' : bigint,
  'totalUsers' : bigint,
  'paidQuotes' : bigint,
  'pendingQuotes' : bigint,
}
export interface InsurancePlan {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'coverageAmount' : bigint,
  'benefits' : Array<string>,
  'monthlyPremium' : bigint,
}
export interface Quote {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'paid' : null },
  'clientName' : string,
  'planId' : bigint,
  'userId' : Principal,
  'createdAt' : bigint,
  'clientEmail' : string,
  'agentName' : string,
  'coverageAmount' : bigint,
  'clientAge' : bigint,
  'planName' : string,
  'paidAt' : [] | [bigint],
  'monthlyPremium' : bigint,
}
export interface UserProfile {
  'username' : string,
  'lastActivity' : bigint,
  'role' : string,
  'isActive' : boolean,
  'email' : string,
  'registeredAt' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInsurancePlan' : ActorMethod<
    [string, string, Array<string>, bigint, bigint],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createQuote' : ActorMethod<[string, bigint, string, bigint], bigint>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllQuotes' : ActorMethod<[], Array<Quote>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlans' : ActorMethod<[], Array<InsurancePlan>>,
  'getQuotesByUser' : ActorMethod<[Principal], Array<Quote>>,
  'getUserById' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], string>,
  'logout' : ActorMethod<[string], boolean>,
  'markQuotePaid' : ActorMethod<[bigint], boolean>,
  'register' : ActorMethod<[string, string, string, string], Principal>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUserActive' : ActorMethod<[Principal, boolean], boolean>,
  'updateUserRole' : ActorMethod<[Principal, string], boolean>,
  'validateSession' : ActorMethod<[string], [] | [[Principal, string]]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];